name: Download latest Gradle build validation scripts
description: "Downloads the latest release of the build validation scripts for Gradle"

inputs:
  token:
    description: "GitHub token"
    required: false
  downloadDevelopmentRelease:
    description: "Downloads the latest development version when 'true'; by default, the latest released version is downloaded"
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download latest Gradle build validation scripts
      run: |
        # Set curl general options
        curlOpts=(--silent --fail --show-error --retry 3 --retry-delay 5 --location)

        # Set authorization header if needed
        if [ ! -z "${{ inputs.token }}" ]; then
          curlOpts+=(--header 'Authorization: Bearer ${{ inputs.token }}')
        fi

        releaseUrl="https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest"
        if [ "${{ inputs.downloadDevelopmentRelease }}" == "true" ]; then
          releaseUrl="https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/tags/development-latest"
        fi

        # Get the download url of the latest development or released version
        downloadUrl=$(curl "${curlOpts[@]}" "$releaseUrl" | jq -c '.assets[] | select(.content_type == "application/zip")' | jq -r .browser_download_url | grep develocity-gradle)

        # Download the scripts
        curl "${curlOpts[@]}" --output develocity-gradle-build-validation.zip $downloadUrl

        # Unzip the downloaded scripts
        unzip -q -o develocity-gradle-build-validation.zip
      shell: bash
