name: Download latest release
description: "Download latest release"

inputs:
  token:
    description: "Github token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get latest release
      run: |
        authHeader=""
        if [ ! -z "${{ inputs.token }}" ]; then
          authHeader="--header 'Authorization: Bearer ${{ inputs.token }}'"
        fi

        # Build Get Latest release data command
        cmdGetLatestReleaseData="curl -s $authHeader https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest"

        # Get latest release download url
        downloadUrl=$($cmdGetLatestReleaseData | jq -c '.assets[] | select(.content_type == "application/zip")' | jq -r .browser_download_url | grep -v maven)

        # Build Get Latest release command
        cmdGetLatestRelease="curl -s -L $authHeader -o gradle-enterprise-gradle-build-validation.zip $downloadUrl"

        # Get latest release
        eval "$cmdGetLatestRelease"

        # Unzip it
        unzip -q -o gradle-enterprise-gradle-build-validation.zip
      shell: bash
