name: Run experiment 5
description: 'Run Gradle Experiment 5'

inputs:
  repositoryUrl:
    description: "Project repository URL"
    required: true
  branch:
    description: "Git Branch"
    required: true
  commitId:
    description: "Commit identifier"
    required: true
  task:
    description: "Gradle task"
    required: true
  seedUrl:
    description: "Seed build scan URL"
    required: true
  projectDir:
    description: "Project directory"
    required: false
    default: .
  gradleEnterpriseUrl:
    description: "Gradle Enterprise URL"
    required: true
  gradleCacheUrl:
    description: "Gradle cache URL"
    required: true
  gradleCachePush:
    description: "Whether to push to remote cache or not"
    required: false
    default: "false"
  gradleCacheUsername:
    description: "Gradle cache username"
    required: false
  gradleCachePassword:
    description: "Gradle cache password"
    required: false
outputs:
  secondBuildScanUrl:
    description: "Second build scan URL"
    value: ${{ steps.run.outputs.secondBuildScanUrl }}

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 5
      id: run
      run: |
        cd gradle-enterprise-gradle-build-validation

        # add instruction to save build scan url
        BUILD_SCAN_FILE=$(pwd)/build-scan-url.txt
        echo "echo \$build_scan_urls > ${BUILD_SCAN_FILE}" >> 05-validate-remote-build-caching-ci-local.sh

        # run experiment
        ./05-validate-remote-build-caching-ci-local.sh -r ${{ inputs.repositoryUrl }} -b ${{ inputs.branch }} -c ${{ inputs.commitId }} -t ${{ inputs.task }} -p ${{ inputs.projectDir }} -1 ${{ inputs.seedUrl }} -s ${{ inputs.gradleEnterpriseUrl }} -u ${{ inputs.gradleCacheUrl }}

        # set scan url as output
        echo "::set-output name=secondBuildScanUrl::$(cat ${BUILD_SCAN_FILE})"
      env:
        GRADLE_CACHE_PUSH: ${{ inputs.gradleCachePush }}
        GRADLE_CACHE_URL: ${{ inputs.gradleCacheUrl }}
        GRADLE_CACHE_USERNAME: ${{ inputs.gradleCacheUsername }}
        GRADLE_CACHE_PASSWORD: ${{ inputs.gradleCachePassword }}
      shell: bash
