name: Run experiment 5
description: 'Run Gradle Experiment 5'

inputs:
  repositoryUrl:
    description: Project repository URL
    required: true
  branch:
    description: Git Branch
    required: true
  commitId:
    description: Commit identifier
    required: true
  task:
    description: Gradle task
    required: true
  seedUrl:
    description: Seed build scan URL
    required: true
  projectDir:
    description: Project directory
    required: false
    default: .
  gradleEnterpriseUrl:
    description: Gradle Enterprise URL
    required: true
  gradleCacheNodeUrl:
    description: Gradle cache node URL
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 5
      run: |
        cd gradle-enterprise-gradle-build-validation
        ./05-validate-remote-build-caching-ci-local.sh -r ${{ inputs.repositoryUrl }} -b ${{ inputs.branch }} -c ${{ inputs.commitId }} -t ${{ inputs.task }} -p ${{ inputs.projectDir }} -1 ${{ inputs.seedUrl }} -s ${{ inputs.gradleEnterpriseUrl }} -u ${{ inputs.gradleCacheNodeUrl }}
      shell: bash
