name: Check Gradle configuration cache compatibility
description: "Runs the build twice to check that configuration cache entry is restored on second run"

inputs:
  gradleArgs:
    description: "Arguments to pass to Gradle"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
    - name: Run experiment
      id: run
      run: |
        # Need to run both builds within same job id to avoid calculating task graph as
        # configuration cache cannot be reused when environment variable 'GITHUB_ACTION' has changed
        ./gradlew --configuration-cache ${{ inputs.gradleArgs }} 2>&1 | tee -a /tmp/run-1.log
        echo "configCacheStored=$(grep "Configuration cache entry stored" /tmp/run-1.log | wc -l)" >> $GITHUB_OUTPUT
        ./gradlew --configuration-cache ${{ inputs.gradleArgs }} 2>&1 | tee -a /tmp/run-2.log
        echo "configCacheReused=$(grep "Configuration cache entry reused" /tmp/run-2.log | wc -l)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Verify Gradle Configuration Cache was reused
      run: exit 1
      if: steps.run.outputs.configCacheStored != '1' || steps.run.outputs.configCacheReused != '1'
      shell: bash
