name: Run experiment 1
description: "Run Gradle Experiment 1"

inputs:
  gitRepo:
    description: "Git repository URL"
    required: true
  tasks:
    description: "Gradle tasks"
    required: true
  gitBranch:
    description: "Git Branch"
    required: false
  gitCommitId:
    description: "Git Commit"
    required: false
  projectDir:
    description: "Project directory"
    required: false
  args:
    description: "Gradle additional arguments"
    required: false
  gradleEnterpriseUrl:
    description: "Gradle Enterprise URL"
    required: false
  enableGradleEnterprise:
    description: "Enables Gradle Enterprise on a project not already connected"
    required: false

outputs:
  buildScanId1:
    description: "First build scan identifier"
    value: ${{ steps.run.outputs.buildScanId1 }}
  buildScanId2:
    description: "Second build scan identifier"
    value: ${{ steps.run.outputs.buildScanId2 }}

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 1
      id: run
      run: |
        cd gradle-enterprise-gradle-build-validation

        # add instructions to save build scan urls
        BUILD_SCAN_FILE_1=$(pwd)/exp1-build-scan-url-1.txt
        BUILD_SCAN_FILE_2=$(pwd)/exp1-build-scan-url-2.txt
        echo "echo \${build_scan_urls[0]} > ${BUILD_SCAN_FILE_1}" >> 01-validate-incremental-building.sh
        echo "echo \${build_scan_urls[1]} > ${BUILD_SCAN_FILE_2}" >> 01-validate-incremental-building.sh

        EXTRA_ARGS=""
        if [ ! -z "${{ inputs.gitBranch }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -b ${{ inputs.gitBranch }}"
        fi
        if [ ! -z "${{ inputs.gitCommitId }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -c ${{ inputs.gitCommitId }}"
        fi
        if [ ! -z "${{ inputs.projectDir }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -p ${{ inputs.projectDir }}"
        fi
        if [ ! -z "${{ inputs.args }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -a ${{ inputs.args }}"
        fi
        if [ ! -z "${{ inputs.gradleEnterpriseUrl }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -s ${{ inputs.gradleEnterpriseUrl }}"
        fi
        if [ ! -z "${{ inputs.enableGradleEnterprise }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -e"
        fi

        # run experiment
        ./01-validate-incremental-building.sh -r ${{ inputs.gitRepo }} -t ${{ inputs.tasks }} $EXTRA_ARGS

        # set scan url as output
        echo "::set-output name=buildScanId1::$(cat ${BUILD_SCAN_FILE_1} | sed 's:.*/::')"
        echo "::set-output name=buildScanId2::$(cat ${BUILD_SCAN_FILE_2} | sed 's:.*/::')"
      shell: bash
