name: Run experiment 1
description: "Run Gradle Experiment 1"

inputs:
  gitRepo:
    description: "Git repository URL"
    required: true
  tasks:
    description: "Gradle tasks"
    required: true
  gitBranch:
    description: "Git Branch"
    required: false
  gitCommitId:
    description: "Git Commit"
    required: false
  projectDir:
    description: "Project directory"
    required: false
  args:
    description: "Gradle additional arguments"
    required: false
  gradleEnterpriseUrl:
    description: "Gradle Enterprise URL"
    required: false
  enableGradleEnterprise:
    description: "Enables Gradle Enterprise on a project not already connected"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 1
      id: run
      run: |
        cd gradle-enterprise-gradle-build-validation

        EXTRA_ARGS=""
        if [ ! -z "${{ inputs.gitBranch }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -b ${{ inputs.gitBranch }}"
        fi
        if [ ! -z "${{ inputs.gitCommitId }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -c ${{ inputs.gitCommitId }}"
        fi
        if [ ! -z "${{ inputs.projectDir }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -p ${{ inputs.projectDir }}"
        fi
        if [ ! -z "${{ inputs.args }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -a ${{ inputs.args }}"
        fi
        if [ ! -z "${{ inputs.gradleEnterpriseUrl }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -s ${{ inputs.gradleEnterpriseUrl }}"
        fi
        if [ ! -z "${{ inputs.enableGradleEnterprise }}" ]; then
          EXTRA_ARGS="$EXTRA_ARGS -e"
        fi

        # run experiment
        ./01-validate-incremental-building.sh -r ${{ inputs.gitRepo }} -t ${{ inputs.tasks }} $EXTRA_ARGS
      shell: bash
