name: Verify Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build -i
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Extract build validation Scripts
        working-directory: build/distributions
        run: |
          unzip -o gradle-enterprise-gradle-build-validation-*.zip
          unzip -o gradle-enterprise-maven-build-validation-*.zip
      - name: Run Gradle Experiment 01
        working-directory: build/distributions/gradle-enterprise-gradle-build-validation
        run: |
          ./01-validate-incremental-building.sh \
            -r https://github.com/etiennestuder/java-ordered-properties \
            -t build \
            -s https://ge.solutions-team.gradle.com
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Gradle Experiment 02
        working-directory: build/distributions/gradle-enterprise-gradle-build-validation
        run: |
          ./02-validate-local-build-caching-same-location.sh \
            -r https://github.com/etiennestuder/java-ordered-properties \
            -t build \
            -s https://ge.solutions-team.gradle.com
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Gradle Experiment 03
        working-directory: build/distributions/gradle-enterprise-gradle-build-validation
        run: |
          ./03-validate-local-build-caching-different-locations.sh \
            -r https://github.com/etiennestuder/java-ordered-properties \
            -t build \
            -s https://ge.solutions-team.gradle.com
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Gradle Experiment 04
        working-directory: build/distributions/gradle-enterprise-gradle-build-validation
        run: |
          ./04-validate-remote-build-caching-ci-ci.sh \
            -1 https://ge.solutions-team.gradle.com/s/xildcv6frocau \
            -2 https://ge.solutions-team.gradle.com/s/m5e7tyzedn562
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Maven Experiment 01
        working-directory: build/distributions/gradle-enterprise-maven-build-validation
        run: |
          ./01-validate-local-build-caching-same-location.sh \
            -r https://github.com/gradle/maven-build-scan-quickstart.git \
            -g test \
            -s https://ge.solutions-team.gradle.com
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Maven Experiment 02
        working-directory: build/distributions/gradle-enterprise-maven-build-validation
        run: |
          ./02-validate-local-build-caching-different-locations.sh \
            -r https://github.com/gradle/maven-build-scan-quickstart.git \
            -g test \
            -s https://ge.solutions-team.gradle.com
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Run Maven Experiment 03
        working-directory: build/distributions/gradle-enterprise-maven-build-validation
        run: |
          ./03-validate-remote-build-caching-ci-ci.sh \
            -1 https://ge.solutions-team.gradle.com/s/oll3ve3wdv2t6 \
            -2 https://ge.solutions-team.gradle.com/s/eaue4kvqnvnay
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
