name: Create Release


on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Enter the confirmation phrase 'PRODUCTION' (without quotes) if you are sure you want to release
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == "PRODUCTION"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          arguments: --stacktrace --info githubRelease -PfinalRelease
