name: Cross Platform Tests

on: [ workflow_dispatch ]

jobs:
  validate-on-unix-like-systems:
    name: Validate on Unix-like systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download and Extract Build Validation Scripts
        shell: bash
        run: |
          curl -s "https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest" | grep "browser_download_url" | grep "gradle-enterprise-gradle-build-validation" | cut -d '"' -f 4 | xargs -n 1 curl -s -L -O 
          unzip -q -o gradle-enterprise-gradle-build-validation-*.zip
      - name: Run Gradle Experiment 01
        shell: bash
        run: |
          cd gradle-enterprise-gradle-build-validation
          ./01-validate-incremental-building.sh -r https://github.com/etiennestuder/java-ordered-properties -t build -s https://ge.solutions-team.gradle.com
