name: Cross Platform Tests

on: [ workflow_dispatch ]

jobs:
  test-across-platforms:
    name: Test Across Platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        java-version: [ '8', '11', '17' ]
        include:
          - os: windows-2019
            shell: wsl-bash
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    steps:
      - name: Setup WSL
        if: ${{ runner.os == 'Windows' }}
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
      - name: Update and Install dependencies
        if: ${{ runner.os == 'Windows' }}
        run: |
          sudo apt-get install -y curl unzip wget apt-transport-https gnupg
      - name: Setup JDK ${{ matrix.java-version }} on WSL
        if: ${{ runner.os == 'Windows' }}
        run: |
          wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo apt-key add -
          echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
          sudo apt-get update
          sudo apt-get install -y temurin-${{ matrix.java-version }}-jdk    
      - name: Setup JDK ${{ matrix.java-version }}
        if: ${{ runner.os != 'Windows' }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Download and Extract Build Validation Scripts
        run: |
          curl -L -O https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/development-latest/gradle-enterprise-gradle-build-validation-dev.zip
          unzip -o gradle-enterprise-gradle-build-validation-*.zip
      - name: Run Gradle Experiment 01
        run: |
          cd gradle-enterprise-gradle-build-validation
          ./01-validate-incremental-building.sh -r https://github.com/etiennestuder/java-ordered-properties -t build -s https://ge.solutions-team.gradle.com
